spring:
  webflux:
    static-path-pattern: "/**"
  web:
    resources:
      static-locations:
      - "classpath:/static/"

mario:
    logFolder: "\\home\\logs"
    displayScore: true

logging:
  file:
    name: mario.log
    path: "\\home\\logs"
  level:
    root: ERROR
    org.springframework.web: ERROR
    at.jku.cg.binter.infinitemario: ERROR
    at.jku.cg.binter.infinitemario.io: ERROR
    at.jku.cg.binter.infinitemario.log: ERROR
    at.jku.cg.binter.infinitemario.log.session: ERROR
    reactor.Flux.Map: ERROR